"use strict";
const $=s=>{const node=document.querySelector(s);if(node&&!node.get)node.get=()=>node;return node},$$=s=>[...document.querySelectorAll(s)];
const AS="assets/";
const emotionData={joy:{label:"радостно",bonus:"Удвоение следующих трёх кристаллов",image:AS+"emotions/emotion-joy.png"},angry:{label:"сердито",bonus:"Щит от одного столкновения",image:AS+"emotions/emotion-angry.png"},sad:{label:"грустно",bonus:"Препятствия замедлены на 7 секунд",image:AS+"emotions/emotion-sad.png"},surprised:{label:"удивлённо",bonus:"Кристаллы притягиваются 7 секунд",image:AS+"emotions/emotion-surprised.png"}};
const state={screen:"start",running:false,paused:false,ended:false,lives:3,score:0,correct:0,regularCollected:0,progress:0,y:.48,vy:0,keys:{up:false,down:false},voice:false,voiceInput:false,voiceLevel:0,voiceUntil:0,mic:"waiting",micUnavailable:false,audioContext:null,stream:null,analyser:null,data:null,threshold:.035,loud:false,entities:[],landing:null,obstaclePlan:[],nextObstacle:0,obstacleStats:[],frame:0,last:0,invulnerableUntil:0,shield:0,double:0,slowUntil:0,magnetUntil:0,nextCrystalProgress:0,crystalGroupIndex:0,crystalsSpawnedByQuarter:[0,0,0,0],sfx:true,sfxContext:null,sfxMaster:null,sfxNodes:new Set,sfxEvents:{crystal:0,collision:0},config:null,testMode:new URLSearchParams(location.search).get("test")==="1"};
window.__VOLCANO_STATE__=state;
const screens={start:$("#startScreen"),instructions:$("#instructionsScreen"),game:$("#gameScreen"),victory:$("#victoryScreen"),retry:$("#retryScreen")};
function show(name){state.screen=name;Object.entries(screens).forEach(([key,node])=>node.classList.toggle("active",key===name))}
function positionBackgroundLayer(selector,offset){const layer=$(selector),height=Math.round(screens.game.getBoundingClientRect().height);if(!layer||!height)return;const panelWidth=Math.round(height*2700/941),stride=panelWidth-3,wrapped=((offset%stride)+stride)%stride,x=-wrapped;const panels=[...layer.querySelectorAll(".bg-panel")];panels.forEach((panel,index)=>{panel.style.width=`${panelWidth}px`;panel.style.transform=`translate3d(${x+index*stride}px,0,0)`})}
function positionBackgrounds(){positionBackgroundLayer(".far-bg",state.progress*220);positionBackgroundLayer(".near-bg",state.progress*520)}
function resizePlayer(){const scene=screens.game.getBoundingClientRect();$("#yashka").style.top=`${state.y*scene.height-$("#yashka").offsetHeight/2}px`}
function renderLives(){const box=$("#lives");if(box.dataset.value===String(state.lives))return;box.dataset.value=String(state.lives);box.setAttribute("aria-label",`Жизней: ${state.lives} из 3`);box.innerHTML="";for(let i=0;i<3;i++){const img=document.createElement("img"),active=i<state.lives;img.className=`life-crystal ${active?"whole":"lost"}`;img.src=active?"../assets/ui/crystal-whole.png":"../assets/ui/crystal-lost.png";img.alt=active?"Целый кристалл жизни":"Потерянный кристалл жизни";box.append(img)}}
function render(){renderLives();$("#score").textContent=state.score;$("#taskProgress").textContent=`Задание ${Math.min(10,Math.floor(state.progress*10)+1)} из 10`;const badges=[];if(state.shield)badges.push("Щит");if(state.double)badges.push(`×2 (${state.double})`);if(performance.now()<state.slowUntil)badges.push("Замедление");if(performance.now()<state.magnetUntil)badges.push("Притяжение");$("#effectBadges").innerHTML=badges.map(x=>`<span>${x}</span>`).join("");$("#yashka").classList.toggle("shielded",!!state.shield)}
function setMic(mode,text){state.mic=mode;const card=$("#micStatus");card.className="mic-card "+mode;$("#micText").textContent=text}
function ensureSfxAudio(){if(!state.sfxContext){const AudioCtx=window.AudioContext||window.webkitAudioContext;if(!AudioCtx)return null;state.sfxContext=new AudioCtx;state.sfxMaster=state.sfxContext.createGain();state.sfxMaster.gain.value=state.sfx?1:0;state.sfxMaster.connect(state.sfxContext.destination)}if(state.sfx&&state.sfxContext.state==="suspended")state.sfxContext.resume().catch(()=>{});return state.sfxContext}
function trackSfx(node){state.sfxNodes.add(node);node.addEventListener("ended",()=>state.sfxNodes.delete(node),{once:true});return node}
function stopSfx(){for(const node of state.sfxNodes){try{node.stop()}catch{}}state.sfxNodes.clear()}
function playCrystalSfx(){if(!state.sfx||state.paused||state.ended)return;const ctx=ensureSfxAudio();if(!ctx)return;state.sfxEvents.crystal++;const now=ctx.currentTime,osc=trackSfx(ctx.createOscillator()),gain=ctx.createGain(),pitch=.96+Math.random()*.09;osc.type="sine";osc.frequency.setValueAtTime(920*pitch,now);osc.frequency.exponentialRampToValueAtTime(1320*pitch,now+.18);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.045,now+.012);gain.gain.exponentialRampToValueAtTime(.0001,now+.24);osc.connect(gain).connect(state.sfxMaster);osc.start(now);osc.stop(now+.25)}
function playCollisionSfx(){if(!state.sfx||state.paused||state.ended)return;const ctx=ensureSfxAudio();if(!ctx)return;state.sfxEvents.collision++;const now=ctx.currentTime,length=Math.ceil(ctx.sampleRate*.36),buffer=ctx.createBuffer(1,length,ctx.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/length,2);const source=trackSfx(ctx.createBufferSource()),filter=ctx.createBiquadFilter(),gain=ctx.createGain();filter.type="lowpass";filter.frequency.value=520;filter.Q.value=.6;gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.075,now+.018);gain.gain.exponentialRampToValueAtTime(.0001,now+.36);source.buffer=buffer;source.connect(filter).connect(gain).connect(state.sfxMaster);source.start(now);source.stop(now+.37)}
function toggleSound(){state.sfx=!state.sfx;if(state.sfx){ensureSfxAudio();if(state.sfxMaster)state.sfxMaster.gain.setValueAtTime(1,state.sfxContext.currentTime)}else{if(state.sfxMaster)state.sfxMaster.gain.setValueAtTime(0,state.sfxContext.currentTime);stopSfx()}[$("#hudSoundButton"),$("#startSound")].forEach(button=>{button.textContent="♫";button.style.opacity=state.sfx?'1':'.55';button.setAttribute("aria-pressed",String(!state.sfx));button.setAttribute("aria-label",state.sfx?"Выключить звуки":"Включить звуки")})}
async function initMic(){state.micUnavailable=false;if(!navigator.mediaDevices?.getUserMedia){state.micUnavailable=true;setMic("quiet","касание без микрофона");return}try{state.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:false});state.audioContext=new (window.AudioContext||window.webkitAudioContext)();const source=state.audioContext.createMediaStreamSource(state.stream);state.analyser=state.audioContext.createAnalyser();state.analyser.fftSize=1024;state.data=new Uint8Array(state.analyser.fftSize);source.connect(state.analyser);setMic("quiet","тишина")}catch(e){state.micUnavailable=true;setMic("quiet","касание без микрофона")}}
function sampleVoice(now){let raw=false,loud=false,rms=0;if(state.keys.space){raw=true;rms=.11}if(state.analyser){state.analyser.getByteTimeDomainData(state.data);let sum=0;for(const n of state.data){const v=(n-128)/128;sum+=v*v}rms=Math.sqrt(sum/state.data.length);raw=rms>state.threshold;loud=rms>.28}const normalized=Math.max(0,Math.min(1,(rms-state.threshold)/(.2-state.threshold)));state.voiceLevel+=((raw?normalized:0)-state.voiceLevel)*.22;state.voiceInput=raw;if(raw)state.voiceUntil=now+900;state.voice=now<state.voiceUntil;state.loud=loud;setMic(loud?"loud":state.voice?"active":"quiet",loud?"слишком громко":state.voice?"ветер активен":"тишина");$("#yashka").src=state.voice?AS+"glider/yashka-glider-voice-active.png":AS+"glider/yashka-glider-idle.png"}
function spawn(type,x,y,extra={}){const img=document.createElement("img");img.className=`entity ${type} ${extra.kind||""}`;img.src=extra.src;img.dataset.type=type;img.alt="";$("#world").append(img);const e={el:img,type,x,y,hit:false,...extra};state.entities.push(e);return e}
function buildObstaclePlan(){const ranges=[[.03,.22],[.27,.47],[.52,.72],[.765,.875]],plan=[];let top=true,steamLane=0;ranges.forEach(([start,end],quarter)=>{const span=end-start;plan.push({at:start+span*.08,type:"peak",kind:top?"hanging":"ground",quarter});top=!top;plan.push({at:start+span*.25,type:"steam",lane:steamLane++%3,quarter});plan.push({at:start+span*.42,type:"peak",kind:top?"hanging":"ground",quarter});top=!top;plan.push({at:start+span*.78,type:"steam",lane:steamLane++%3,quarter})});state.obstaclePlan=plan.sort((a,b)=>a.at-b.at);state.nextObstacle=0;state.obstacleStats=Array.from({length:4},()=>({top:0,bottom:0,steam:0}))}
function buildRoute(){$("#world").innerHTML="";state.entities=[];buildObstaclePlan();const pool=["joy","angry","sad","surprised"].sort(()=>Math.random()-.5);spawn("emotion",2.05,.34,{emotion:pool[0],src:emotionData[pool[0]].image});spawn("emotion",3.85,.62,{emotion:pool[1],src:emotionData[pool[1]].image})}
function generateObstacles(){while(state.nextObstacle<state.obstaclePlan.length&&state.progress>=state.obstaclePlan[state.nextObstacle].at){const item=state.obstaclePlan[state.nextObstacle++],stats=state.obstacleStats[item.quarter];if(item.type==="peak"){const top=item.kind==="hanging";spawn("obstacle",1.12,top?-.12:0,{kind:item.kind,src:AS+`obstacles/${top?"hanging-rock":"ground-rock"}.png`,spawnQuarter:item.quarter});stats[top?"top":"bottom"]++}else{const heights=[.2,.43,.66];spawn("obstacle",1.12,heights[item.lane],{kind:"steam",src:AS+"obstacles/steam-cloud.png",spawnQuarter:item.quarter});stats.steam++}}}
function safeCrystalHeight(x,preferred){let y=preferred;for(const e of state.entities){if(e.hit||e.type!=="obstacle"||Math.abs(e.x-x)>.2)continue;if(e.kind==="hanging")y=Math.max(y,.61);else if(e.kind==="ground")y=Math.min(y,.2);else if(e.kind==="steam")y=y<.45?.2:.7}return Math.max(.18,Math.min(.72,y))}
function spawnCrystalGroup(){const count=3+Math.floor(Math.random()*4),baseX=1.04,lane=[.24,.46,.66][state.crystalGroupIndex%3],quarter=state.progress<.25?0:state.progress<.5?1:state.progress<.75?2:3;for(let i=0;i<count;i++){const x=baseX+i*.085,y=safeCrystalHeight(x,lane+Math.sin(i*.9)*.045);spawn("crystal",x,y,{src:AS+"collectibles/crystal.png",spawnQuarter:quarter})}state.crystalsSpawnedByQuarter[quarter]+=count;state.crystalGroupIndex++;state.nextCrystalProgress+=.095+Math.random()*.025;if(state.progress<.75&&state.nextCrystalProgress>.78)state.nextCrystalProgress=.78}
function generateCrystals(){while(state.nextCrystalProgress<=.82&&state.progress>=state.nextCrystalProgress)spawnCrystalGroup()}
function entityRect(e,scene){const left=e.x*scene.width,top=e.y*scene.height;if(e.kind==="steam"){const stamp=performance.now();if(e.steamLastTime===undefined){e.steamLastTime=stamp;e.steamPhase=0}else{const elapsed=Math.min(.05,Math.max(0,(stamp-e.steamLastTime)/1000));e.steamPhase+=elapsed*Math.PI*2/3.6;e.steamLastTime=stamp}const wave=Math.sin(e.steamPhase),breath=Math.sin(e.steamPhase-.65);e.el.style.transform=`translate3d(${left}px,${top+wave*8}px,0) scale(${1+breath*.04})`}else{e.el.style.transform=`translate3d(${left}px,${top}px,0)`}const rect=e.el.getBoundingClientRect();if(e.kind==="ground"){const insetX=rect.width*.14,insetTop=rect.height*.08;return{left:rect.left+insetX,top:rect.top+insetTop,right:rect.right-insetX,bottom:rect.bottom,width:rect.width-insetX*2,height:rect.height-insetTop}}if(e.kind==="hanging"){const insetX=rect.width*.14,insetBottom=rect.height*.08;return{left:rect.left+insetX,top:rect.top,right:rect.right-insetX,bottom:rect.bottom-insetBottom,width:rect.width-insetX*2,height:rect.height-insetBottom}}if(e.type!=="emotion"&&e.type!=="crystal")return rect;const ratio=e.type==="emotion"?.38:.75,margin=Math.max(e.type==="emotion"?18:32,Math.min(rect.width,rect.height)*ratio);return{left:rect.left-margin,top:rect.top-margin,right:rect.right+margin,bottom:rect.bottom+margin,width:rect.width+margin*2,height:rect.height+margin*2}}
function overlaps(a,b,pad=.18){return a.left+a.width*pad<b.right-b.width*pad&&a.right-a.width*pad>b.left+b.width*pad&&a.top+a.height*pad<b.bottom-b.height*pad&&a.bottom-a.height*pad>b.top+b.height*pad}
function collect(e){if(e.hit)return;if(e.type==="crystal"&&!state.voice&&!state.micUnavailable)return;e.hit=true;e.el.remove();if(e.type==="crystal"){playCrystalSfx();window.MirProgress?.correct('volcano');state.regularCollected++;state.correct++;state.score++;if(state.double)state.double--}else{openEmotion(e.emotion)}render()}
function collide(now){if(state.landing||now<state.invulnerableUntil)return;playCollisionSfx();state.shield=0;state.lives=Math.max(0,state.lives-1);state.invulnerableUntil=now+2000;$("#yashka").classList.add("hit");setTimeout(()=>$("#yashka").classList.remove("hit"),900);render();if(state.lives<=0)finish(false)}
function openEmotion(kind){state.paused=true;const d=emotionData[kind];$("#emotionImage").src=d.image;$("#emotionPrompt").textContent=`Произнеси С-С-С ${d.label}!`;$("#emotionVoice").textContent="Произнесите звук…";$("#emotionVoice").classList.remove("heard");$("#emotionOverlay").hidden=false;state.pendingEmotion=kind}
function completeEmotion(){const kind=state.pendingEmotion;if(!kind)return;state.score++;state.correct++;window.MirProgress?.correct('volcano');if(kind==="joy")state.double=3;if(kind==="angry")state.shield=1;if(kind==="sad")state.slowUntil=performance.now()+7000;if(kind==="surprised")state.magnetUntil=performance.now()+7000;state.pendingEmotion=null;$("#emotionOverlay").hidden=true;state.paused=false;state.last=performance.now();render()}
function beginLanding(){if(state.landing)return;for(const e of state.entities)e.el.remove();state.entities=[];const platform=spawn("platform",1.08,.7,{src:AS+"effects/landing-platform.png"}),scene=screens.game.getBoundingClientRect(),player=$("#yashka"),rect=player.getBoundingClientRect();state.voice=false;state.voiceUntil=0;state.keys.up=false;state.keys.down=false;player.src=AS+"glider/yashka-glider-idle.png";player.style.left=`${rect.left-scene.left}px`;player.style.top=`${rect.top-scene.top}px`;player.style.transform="none";state.progress=Math.min(.9,state.progress);state.landing={phase:"platform-entry",platform,playerX:rect.left-scene.left,playerY:rect.top-scene.top,elapsed:0,targetPlatformX:.395,complete:false}}
function updateLanding(dt){const landing=state.landing,scene=screens.game.getBoundingClientRect(),player=$("#yashka"),platform=landing.platform;if(!landing||landing.complete)return;landing.elapsed+=dt;if(landing.phase==="platform-entry"){platform.x=Math.max(landing.targetPlatformX,platform.x-dt*.145);state.progress=Math.min(.94,state.progress+dt/(state.testMode?12:state.config.route.durationSeconds));entityRect(platform,scene);positionBackgrounds();if(platform.x<=landing.targetPlatformX+.0001){platform.x=landing.targetPlatformX;const platformRect=entityRect(platform,scene),platformSurface=platformRect.top+platformRect.height*.33;landing.phase="descend";landing.elapsed=0;landing.startX=landing.playerX;landing.startY=landing.playerY;landing.targetX=platformRect.left-scene.left+platformRect.width/2-player.offsetWidth/2;landing.targetY=platformSurface-scene.top-player.offsetHeight*.79;landing.platformRect={left:platformRect.left,top:platformRect.top};landing.startProgress=state.progress}}else if(landing.phase==="descend"){const t=Math.min(1,landing.elapsed/1.8),ease=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;landing.playerX=landing.startX+(landing.targetX-landing.startX)*ease;landing.playerY=landing.startY+(landing.targetY-landing.startY)*ease;player.style.left=`${landing.playerX}px`;player.style.top=`${landing.playerY}px`;player.style.transform=`rotate(${(1-ease)*-3}deg)`;state.progress=Math.min(.99,landing.startProgress+(.99-landing.startProgress)*ease);entityRect(platform,scene);if(t>=1){player.style.left=`${landing.targetX}px`;player.style.top=`${landing.targetY}px`;player.style.transform="none";landing.playerX=landing.targetX;landing.playerY=landing.targetY;landing.phase="settle";landing.elapsed=0}}else if(landing.phase==="settle"){entityRect(platform,scene);if(landing.elapsed>=.65){landing.complete=true;state.progress=1;render();finish(true);return}}render()}
function update(now,dt){if(state.paused||!state.running)return;if(state.landing){updateLanding(dt);return}sampleVoice(now);const duration=state.testMode?12:state.config.route.durationSeconds;state.progress+=dt/duration;if(state.progress>=.9){beginLanding();updateLanding(dt);return}generateObstacles();generateCrystals();const direction=(state.keys.down?1:0)-(state.keys.up?1:0),keyboardActive=direction!==0;if(keyboardActive)state.vy+=(direction*.85-state.vy*5)*dt;else if(state.voiceInput&&!state.micUnavailable){const voiceTarget=.72-state.voiceLevel*.53;state.vy+=((voiceTarget-state.y)*3.4-state.vy*4.5)*dt}else state.vy+=-state.vy*5*dt;state.y=Math.max(.19,Math.min(.79,state.y+state.vy*dt));resizePlayer();const bob=keyboardActive||state.voiceInput?0:Math.sin(now/420)*4,tilt=Math.max(-8,Math.min(8,state.vy*24));$("#yashka").style.transform=`translateY(${bob}px) rotate(${tilt}deg)`;const speed=performance.now()<state.slowUntil?.48:1,travel=dt*.145*speed*(state.testMode?6:1);positionBackgrounds();const scene=screens.game.getBoundingClientRect(),player=$("#yashka").getBoundingClientRect();for(const e of state.entities){if(e.hit)continue;e.x-=travel;if(e.type==="crystal"&&now<state.magnetUntil&&e.x<.65&&e.x>.18)e.y+=(state.y-e.y)*dt*1.7;const rect=entityRect(e,scene);if(rect.right<scene.left){e.hit=true;e.el.remove();continue}if((e.type==="crystal"||e.type==="emotion")&&overlaps(player,rect,.28)){if(e.type==="crystal"&&!state.voice&&!state.micUnavailable)continue;collect(e)}else if(e.type==="obstacle"&&overlaps(player,rect,.27))collide(now)}render()}
function loop(now){const dt=Math.min(.035,(now-(state.last||now))/1000);state.last=now;update(now,dt);state.frame=requestAnimationFrame(loop)}
function reset(){window.MirProgress?.startAttempt('volcano');stopSfx();ensureSfxAudio();state.running=true;state.paused=false;state.ended=false;state.landing=null;state.lives=3;state.score=0;state.regularCollected=0;state.progress=0;state.y=.48;state.vy=0;state.voice=false;state.voiceInput=false;state.voiceLevel=0;state.voiceUntil=0;state.shield=0;state.double=0;state.slowUntil=0;state.magnetUntil=0;state.nextCrystalProgress=0;state.crystalGroupIndex=0;state.crystalsSpawnedByQuarter=[0,0,0,0];state.invulnerableUntil=performance.now()+1500;const player=$("#yashka");player.style.left="";player.style.top="";player.style.transform="";buildRoute();generateCrystals();render();show("game");resizePlayer();positionBackgrounds();screens.game.focus();state.last=performance.now()}
function finish(win){if(state.ended)return;state.ended=true;state.running=false;state.paused=true;stopSfx();window.MirProgress?.finish('volcano',{score:state.score,completed:win});localStorage.setItem("mir.volcano.lastScore",state.score);const best=Math.max(state.score,Number(localStorage.getItem("mir.volcano.bestScore")||0));localStorage.setItem("mir.volcano.bestScore",best);if(win){$("#victoryScore").textContent=state.score;$("#victoryCorrect").textContent=state.correct;$("#victoryBest").textContent=best;$("#victoryCollected").textContent=state.regularCollected}else{$("#retryScore").textContent=state.score;$("#retryCorrect").textContent=state.correct;$("#retryCollected").textContent=state.regularCollected}show(win?"victory":"retry")}
function pause(){if(!state.running||state.pendingEmotion)return;state.paused=true;stopSfx();$("#pauseOverlay").hidden=false}
function resume(){state.paused=false;state.last=performance.now();$("#pauseOverlay").hidden=true;screens.game.focus()}
function beginFlight(){state.correct=0;reset()}
function openRules(){state.paused=true;$("#rulesOverlay").hidden=false}
function closeRules(){$("#rulesOverlay").hidden=true;state.paused=false;state.last=performance.now();screens.game.focus()}
$("#startButton").addEventListener("click",()=>{ensureSfxAudio();show("instructions")});$("#startRules").addEventListener("click",()=>show("instructions"));$("#closeInstructions").addEventListener("click",()=>show("start"));$("#flightButton").addEventListener("click",async()=>{beginFlight();initMic()});$("#playAgain").addEventListener("click",beginFlight);$("#retryButton").addEventListener("click",beginFlight);$("#pauseButton").addEventListener("click",pause);$("#resumeButton").addEventListener("click",resume);$("#emotionDone").addEventListener("click",completeEmotion);$("#hudSoundButton").addEventListener("click",toggleSound);$("#startSound").addEventListener("click",toggleSound);$("#rulesButton").addEventListener("click",openRules);$("#closeRules").addEventListener("click",closeRules);$$('.menu-link,.end-actions a').forEach(link=>link.addEventListener("click",stopSfx));window.addEventListener("pagehide",stopSfx);
document.addEventListener("keydown",e=>{if(["ArrowUp","ArrowDown","Space"].includes(e.code))e.preventDefault();if(e.code==="ArrowUp")state.keys.up=true;if(e.code==="ArrowDown")state.keys.down=true;if(e.code==="Space")state.keys.space=true;if(e.code==="Escape"&&state.screen==="game"){state.paused?resume():pause()}});document.addEventListener("keyup",e=>{if(e.code==="ArrowUp")state.keys.up=false;if(e.code==="ArrowDown")state.keys.down=false;if(e.code==="Space")state.keys.space=false});window.addEventListener("blur",()=>{if(state.running&&!state.paused)pause()});window.addEventListener("resize",resizePlayer);setInterval(()=>{if(state.pendingEmotion&&state.voice){$("#emotionVoice").textContent="Голос услышан — взрослый может нажать «Готово!»";$("#emotionVoice").classList.add("heard")}},120);
const previewParams=new URLSearchParams(location.search);if(previewParams.get("preview")==="retry"){const previewScore=Number(previewParams.get("score")||localStorage.getItem("mir.volcano.lastScore")||0),previewBest=Math.max(previewScore,Number(localStorage.getItem("mir.volcano.bestScore")||0));$("#retryScore").textContent=previewScore;$("#retryBest").textContent=previewBest}
window.addEventListener("resize",positionBackgrounds);
fetch("game-config.json").then(r=>r.json()).then(c=>{state.config=c;render();state.frame=requestAnimationFrame(loop);const preview=new URLSearchParams(location.search).get("preview");if(preview==="game")reset();if(preview==="victory"){show("victory");$("#victoryScore").textContent=850}if(preview==="retry")show("retry")}).catch(e=>{console.error(e);$("#startButton").setAttribute("aria-label","Ошибка загрузки игры")});
