(function(){
  "use strict";
  const A="assets/profile/",AVATAR_BASE="MIR_PROFILE_RATING_ASSETS/avatars/",avatars=[
    {id:"rabbit",name:"Зайчонок",file:"01-rabbit.png",avatarDisplay:{scale:1.06,x:0,y:3}},
    {id:"fox",name:"Лисёнок",file:"02-fox.png",avatarDisplay:{scale:1.15,x:0,y:4}},
    {id:"chipmunk",name:"Бурундучок",file:"03-chipmunk.png",avatarDisplay:{scale:1.14,x:0,y:3}},
    {id:"squirrel",name:"Белочка",file:"04-squirrel.png",avatarDisplay:{scale:1.08,x:0,y:4}},
    {id:"owl",name:"Совёнок",file:"05-owl.png",avatarDisplay:{scale:1.14,x:0,y:3}},
    {id:"bear",name:"Медвежонок",file:"06-bear.png",avatarDisplay:{scale:1.14,x:0,y:3}},
    {id:"hedgehog",name:"Ёжик",file:"07-hedgehog.png",avatarDisplay:{scale:1.14,x:0,y:3}},
    {id:"raccoon",name:"Енотик",file:"08-raccoon.png",avatarDisplay:{scale:1.14,x:0,y:3}},
    {id:"deer",name:"Оленёнок",file:"09-deer.png",avatarDisplay:{scale:1.06,x:0,y:3}},
    {id:"mouse",name:"Мышонок",file:"10-mouse.png",avatarDisplay:{scale:1.12,x:0,y:3}},
    {id:"beaver",name:"Бобрёнок",file:"11-beaver.png",avatarDisplay:{scale:1.15,x:0,y:3}},
    {id:"otter",name:"Выдрёнок",file:"12-otter.png",avatarDisplay:{scale:1.15,x:0,y:3}},
    {id:"badger",name:"Барсучонок",file:"13-badger.png",avatarDisplay:{scale:1.14,x:0,y:3}},
    {id:"lynx",name:"Рысёнок",file:"14-lynx.png",avatarDisplay:{scale:1.06,x:0,y:3}},
    {id:"wolf",name:"Волчонок",file:"15-wolf.png",avatarDisplay:{scale:1.1,x:0,y:3}}
  ],avatarFiles=avatars.map(x=>x.file),avatarNames=avatars.map(x=>x.name);
  const $=s=>document.querySelector(s),gate=$("#profileGate"),createView=$("#createView"),chooseView=$("#chooseView"),profileModal=$("#profileModal"),ratingModal=$("#ratingModal"),picker=$("#avatarPicker");let selectedAvatar=0,lastFocus=null,ratingTab="mine",lastGeneratedNick="";
  const avatarIndex=value=>{const numeric=Number(value);return Number.isInteger(numeric)&&numeric>=1&&numeric<=avatars.length?numeric:1},avatarSrc=value=>`${AVATAR_BASE}${avatars[avatarIndex(value)-1].file}`;
  function avatarVars(value){const display=avatars[avatarIndex(value)-1].avatarDisplay;return`--avatar-scale:${display.scale};--avatar-x:${display.x}%;--avatar-y:${display.y}%`}
  function decorateAvatars(root=document){root.querySelectorAll('img[src*="/avatars/"]:not(.avatar-animal)').forEach(img=>{const file=decodeURIComponent(img.src).split("/").pop(),avatar=avatarFiles.indexOf(file)+1;if(!avatar)return;const shell=document.createElement("span"),classes=[...img.classList];shell.className=`avatar-shell ${classes.join(" ")}`.trim();shell.style.cssText=avatarVars(avatar);shell.dataset.avatar=avatar;img.className="avatar-animal";img.before(shell);shell.append(img)})}
  function refreshAvatarDisplay(root=document){root.querySelectorAll('img.avatar-animal[src*="/avatars/"]').forEach(img=>{const avatar=avatarFiles.indexOf(decodeURIComponent(img.src).split("/").pop())+1;if(avatar&&img.parentElement)img.parentElement.style.cssText=avatarVars(avatar)})}
  const rankSrc=r=>`${A}ranks/${r.image}`;
  function escapeHtml(value){const node=document.createElement("span");node.textContent=String(value);return node.innerHTML}
  function updateCreatePreview(){const preview=$("#createAvatarPreview"),placeholder=$("#createAvatarPlaceholder");if(!preview)return;preview.hidden=!selectedAvatar;placeholder.hidden=!!selectedAvatar;if(selectedAvatar){preview.src=avatarSrc(selectedAvatar);preview.alt=`Выбранный аватар: ${avatarNames[selectedAvatar-1]}`}}
  function renderPicker(){picker.innerHTML=avatars.map((avatar,i)=>`<button class="avatar-choice" type="button" role="radio" aria-checked="${i+1===selectedAvatar}" aria-label="${avatar.name}" data-avatar="${i+1}" data-avatar-id="${avatar.id}"><img src="${AVATAR_BASE}${avatar.file}" alt=""><span class="avatar-choice-name">${avatar.name}</span></button>`).join("");picker.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{selectedAvatar=Number(button.dataset.avatar);picker.classList.remove("needs-choice");$("#createError").textContent="";renderPicker();updateCreatePreview()}));updateCreatePreview()}
  function showCreate(fromProfiles=false){selectedAvatar=0;lastGeneratedNick="";createView.hidden=false;chooseView.hidden=true;$("#backToProfiles").hidden=!fromProfiles;$("#profileNick").value="";$("#createError").textContent="";renderPicker();requestAnimationFrame(()=>$("#profileNick").focus())}
  function showChooser(){const data=MirProgress.load();createView.hidden=true;chooseView.hidden=false;$("#profileChoices").innerHTML=data.profiles.map(profile=>`<button class="profile-choice" type="button" data-profile="${profile.id}" aria-label="Выбрать исследователя ${escapeHtml(profile.nick)}"><img src="${avatarSrc(profile.avatar)}" alt="${avatarNames[profile.avatar-1]}"><strong>${escapeHtml(profile.nick)}</strong><span>${MirProgress.rankFor(profile.sparks).name}</span><span>${profile.sparks} искр</span></button>`).join("");$("#profileChoices").querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>{MirProgress.select(button.dataset.profile);gate.hidden=true;syncHeader();button.blur()}));requestAnimationFrame(()=>$("#profileChoices button")?.focus())}
  function openGate(){gate.hidden=false;const data=MirProgress.load();data.profiles.length?showChooser():showCreate(false)}
  function syncHeader(){const p=MirProgress.active(),button=$("#profileButton");button.hidden=!p;if(!p)return;$("#profileChipAvatar").src=avatarSrc(p.avatar);$("#profileChipAvatar").alt=avatarNames[p.avatar-1];$("#profileChipName").textContent=p.nick;$("#profileChipSparks").textContent=p.sparks}
  function progressData(p){const rank=MirProgress.rankFor(p.sparks),next=MirProgress.nextRank(p.sparks),span=next?next.min-rank.min:1,value=next?Math.min(100,(p.sparks-rank.min)/span*100):100;return{rank,next,value}}
  function houseTabs(active){return`<div class="house-tabs" role="tablist" aria-label="Личное пространство"><button type="button" role="tab" data-house-tab="profile" aria-selected="${active==="profile"}">Мой профиль</button><button type="button" role="tab" data-house-tab="rating" aria-selected="${active==="rating"}">Рейтинг участников</button></div>`}
  function mountHouseAvatar(){const panel=profileModal.querySelector(".profile-details"),profile=MirProgress.active(),activeTab=panel.querySelector('[data-house-tab][aria-selected="true"]')?.dataset.houseTab;panel.querySelector(".house-avatar-anchor")?.remove();if(!profile||!activeTab)return;const anchor=document.createElement("div");anchor.className="house-avatar-anchor";anchor.style.cssText=avatarVars(profile.avatar);anchor.innerHTML=`<div class="house-avatar-slot house-avatar-${activeTab}"><img class="house-avatar-animal avatar-animal" src="${avatarSrc(profile.avatar)}" alt="${avatarNames[profile.avatar-1]}"></div>`;panel.append(anchor)}
  function bindHouseTabs(){mountHouseAvatar();document.querySelectorAll("[data-house-tab]").forEach(button=>button.addEventListener("click",()=>openProfile(button.dataset.houseTab)))}
  function openProfile(tab="profile"){const p=MirProgress.active();if(!p)return openGate();const wasHidden=profileModal.hidden;if(wasHidden)lastFocus=document.activeElement;if(tab==="rating"){$("#profileContent").innerHTML=`${houseTabs("rating")}<h2 id="profileTitle" class="house-title">Рейтинг участников</h2><div class="rating-list house-rating">${rankingRows()}</div>`;profileModal.hidden=false;bindHouseTabs();if(wasHidden)requestAnimationFrame(()=>profileModal.querySelector(".panel-close").focus());return}const {rank,next,value}=progressData(p),awards=[`<span class="award"><img src="${rankSrc(rank)}" alt="${rank.name}"><b>${rank.name}</b></span>`];Object.entries(p.completed).filter(([,count])=>count>0).forEach(([game,count])=>awards.push(`<span class="award"><img src="${A}ui/speech-spark.png" alt=""><b>${MirProgress.games[game]} × ${count}</b></span>`));$("#profileContent").innerHTML=`${houseTabs("profile")}<div class="profile-hero"><div class="profile-avatar"><img class="animal" src="${avatarSrc(p.avatar)}" alt="${avatarNames[p.avatar-1]}"><img class="frame" src="${A}ui/avatar-frame-selected.png" alt=""></div><div class="profile-head"><h2 id="profileTitle">${escapeHtml(p.nick)}</h2><div class="rank-line"><img src="${rankSrc(rank)}" alt="Значок звания"><span>${rank.name}</span></div><div class="spark-total"><img src="${A}ui/speech-spark.png" alt="Искры речи"><b>${p.sparks}</b><span>искр речи</span></div><div class="rank-progress" aria-label="Прогресс до следующего звания"><span style="width:${value}%"></span></div><small>${next?`До звания «${next.name}»: ${next.min-p.sparks} искр`:`Высшее звание достигнуто!`}</small></div></div><div class="profile-grid"><section class="profile-card"><h3>Лучшие результаты</h3><div class="best-row"><span>Лес звуков</span><b>${p.best.forest||0}</b></div><div class="best-row"><span>Речка слов</span><b>${p.best.river||0}</b></div><div class="best-row"><span>Говорящий вулкан</span><b>${p.best.volcano||0}</b></div></section><section class="profile-card"><h3>Награды</h3><div class="award-list">${awards.join("")}</div></section></div><div class="profile-actions"><button id="switchProfile" class="profile-primary" type="button">Сменить исследователя</button><button id="deleteProfile" class="profile-danger" type="button">Удалить профиль</button></div>`;profileModal.hidden=false;bindHouseTabs();$("#switchProfile").addEventListener("click",()=>{profileModal.hidden=true;MirProgress.clearActive();openGate()});$("#deleteProfile").addEventListener("click",()=>{if(!confirm("Удалить профиль и все результаты? Это действие нельзя отменить"))return;MirProgress.deleteProfile(p.id);profileModal.hidden=true;syncHeader();openGate()});if(wasHidden)requestAnimationFrame(()=>profileModal.querySelector(".panel-close").focus())}
  function closeProfile(){profileModal.hidden=true;syncHeader();lastFocus?.focus()}
  function rankingRows(){const p=MirProgress.active(),all=MirProgress.load().profiles.map(profile=>({nick:profile.nick,avatar:profile.avatar,sparks:profile.sparks,current:profile.id===p?.id})).sort((a,b)=>b.sparks-a.sparks);if(!all.length)return'<p class="empty-rating">В рейтинге пока нет участников</p>';const shown=all.slice(0,10),currentIndex=p?all.findIndex(row=>row.current):-1,podium=[shown[1],shown[0],shown[2]].filter(Boolean).map(row=>podiumHtml(row,all.indexOf(row)+1)).join(""),rest=shown.slice(3).map((row,i)=>rowHtml(row,i+4));if(p&&currentIndex>=10)rest.push(`<div class="rating-divider">Твоя строка</div>${rowHtml(all[currentIndex],currentIndex+1)}`);const portrait=p?`<img class="rating-circle-avatar" src="${avatarSrc(p.avatar)}" alt="">`:"";return `${portrait}<div class="rating-leaderboard"><div class="rating-podium">${podium}</div><div class="rating-list" tabindex="0">${rest.join("")}</div></div>`}
  function podiumHtml(row,place){const rank=MirProgress.rankFor(row.sparks),tone=["gold","silver","bronze"][place-1];return`<article class="rating-row podium-card podium-${tone}${row.current?" current":""}"><div class="podium-place rating-place"><img src="${A}medals/0${place}-${tone}.png" alt="${place} место"><b>${place}</b></div><img class="rating-avatar" src="${avatarSrc(row.avatar)}" alt="${avatarNames[row.avatar-1]}"><strong class="rating-nick">${escapeHtml(row.nick)}${row.current?'<small class="you-tag">Это ты!</small>':""}</strong><span class="rating-rank">${rank.name}</span><span class="rating-sparks"><img src="${A}ui/speech-spark.png" alt=""><b>${row.sparks}</b></span></article>`}
  function rowHtml(row,place){const rank=MirProgress.rankFor(row.sparks),medal=place<=3?`<img src="${A}medals/0${place}-${["gold","silver","bronze"][place-1]}.png" alt="${place} место">`:String(place);return`<div class="rating-row${row.current?" current":""}"><span class="rating-place">${medal}</span><img class="rating-avatar" src="${avatarSrc(row.avatar)}" alt="${avatarNames[row.avatar-1]}"><span>${escapeHtml(row.nick)} ${row.current?'<b class="you-tag">Это ты!</b>':""}</span><span class="rating-rank">${rank.name}</span><span class="rating-sparks"><img src="${A}ui/speech-spark.png" alt=""><b>${row.sparks}</b></span></div>`}
  function renderRating(){const p=MirProgress.active();$("#myTab").setAttribute("aria-selected",String(ratingTab==="mine"));$("#allTab").setAttribute("aria-selected",String(ratingTab==="all"));if(ratingTab==="all"){$("#ratingBody").innerHTML=`<div class="rating-list">${rankingRows()}</div>`;return}if(!p){$("#ratingBody").innerHTML='<p class="empty-rating">Сначала выбери исследователя</p>';return}const rank=MirProgress.rankFor(p.sparks);$("#ratingBody").innerHTML=`<div class="my-success"><img src="${rankSrc(rank)}" alt="${rank.name}"><div><h3>${escapeHtml(p.nick)}</h3><p>${rank.name}</p><strong>${p.sparks} искр</strong><p>Завершено приключений: ${Object.values(p.completed).reduce((a,b)=>a+b,0)}</p></div></div>`}
  function openRating(){lastFocus=document.activeElement;ratingTab="mine";renderRating();ratingModal.hidden=false;requestAnimationFrame(()=>ratingModal.querySelector(".panel-close").focus())}
  function closeRating(){ratingModal.hidden=true;lastFocus?.focus()}
  $("#createProfile").addEventListener("click",()=>{try{MirProgress.create($("#profileNick").value,selectedAvatar);showChooser()}catch(error){$("#createError").textContent=error.message}});$("#profileNick").addEventListener("keydown",event=>{if(event.key==="Enter")$("#createProfile").click()});$("#addProfile").addEventListener("click",()=>showCreate(true));$("#backToProfiles").addEventListener("click",showChooser);$("#profileButton").addEventListener("click",openProfile);$("#ratingButton").addEventListener("click",openRating);document.querySelectorAll("[data-close-profile]").forEach(x=>x.addEventListener("click",closeProfile));document.querySelectorAll("[data-close-rating]").forEach(x=>x.addEventListener("click",closeRating));$("#myTab").addEventListener("click",()=>{ratingTab="mine";renderRating()});$("#allTab").addEventListener("click",()=>{ratingTab="all";renderRating()});document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(!profileModal.hidden)closeProfile();else if(!ratingModal.hidden)closeRating()});addEventListener("mir:profile-change",syncHeader);syncHeader();if(!MirProgress.active())openGate();
  const nickAnimals=avatarNames,qualities=[
    {id:"smart",masculine:"Умный",feminine:"Умная"},
    {id:"curious-learner",masculine:"Любознательный",feminine:"Любознательная"},
    {id:"quick-witted",masculine:"Сообразительный",feminine:"Сообразительная"},
    {id:"observant",masculine:"Наблюдательный",feminine:"Наблюдательная"},
    {id:"attentive",masculine:"Внимательный",feminine:"Внимательная"},
    {id:"inquisitive",masculine:"Любопытный",feminine:"Любопытная"},
    {id:"agile",masculine:"Ловкий",feminine:"Ловкая"},
    {id:"brave",masculine:"Смелый",feminine:"Смелая"}
  ],femaleAnimals=new Set([4]);let lastGeneratedQualityId="";
  function qualityWord(quality,avatar){return femaleAnimals.has(avatar)?quality.feminine:quality.masculine}
  function migrateRemovedQualities(){const removed=new Set(["Находчивый","Находчивая","Пытливый","Пытливая"]),data=MirProgress.load();let changed=false;data.profiles.forEach(profile=>{const old=[...removed].find(word=>profile.nick===word||profile.nick.startsWith(`${word} `));if(!old)return;const quality=qualities[Math.floor(Math.random()*qualities.length)];profile.nick=`${qualityWord(quality,profile.avatar)}${profile.nick.slice(old.length)}`;changed=true});if(changed)MirProgress.save(data)}
  function randomNickname(){const button=$("#nicknameRandomizer");button.classList.remove("rolling");requestAnimationFrame(()=>button.classList.add("rolling"));if(!selectedAvatar){picker.classList.add("needs-choice");$("#createError").textContent="Сначала выбери зверька";setTimeout(()=>picker.classList.remove("needs-choice"),900);return}const available=qualities.filter(quality=>quality.id!==lastGeneratedQualityId),quality=available[Math.floor(Math.random()*available.length)],nickname=`${qualityWord(quality,selectedAvatar)} ${nickAnimals[selectedAvatar-1]}`;lastGeneratedQualityId=quality.id;lastGeneratedNick=nickname;$("#profileNick").value=nickname;$("#profileNick").focus()}
  function setupCreateTools(){const preview=document.createElement("div");preview.className="create-avatar-preview";preview.innerHTML=`<img id="createAvatarPlaceholder" src="${A}ui/speech-spark.png" alt="Сначала выбери зверька"><img id="createAvatarPreview" src="" alt="" hidden>`;createView.append(preview);const label=$(".nick-label"),row=document.createElement("div"),button=document.createElement("button");row.className="nickname-row";label.before(row);row.append(label);button.id="nicknameRandomizer";button.className="nickname-randomizer";button.type="button";button.title="Придумать другой ник";button.setAttribute("aria-label","Сгенерировать новый игровой ник");button.innerHTML=`<img src="${A}ui/nickname-randomizer.png" alt="">`;button.addEventListener("click",randomNickname);row.append(button);$("#createProfile").addEventListener("click",event=>{if(selectedAvatar)return;event.preventDefault();event.stopImmediatePropagation();picker.classList.add("needs-choice");$("#createError").textContent="Сначала выбери зверька";setTimeout(()=>picker.classList.remove("needs-choice"),900)},{capture:true});updateCreatePreview()}
  function migrateAvatarCollection(){const data=MirProgress.load();let changed=false;data.profiles.forEach(profile=>{const index=avatarIndex(profile.avatar),id=avatars[index-1].id;if(profile.avatar!==index){profile.avatar=index;changed=true}if(profile.avatarId!==id){profile.avatarId=id;changed=true}});if(changed)MirProgress.save(data)}
  function enableFullGeneratedNicks(){const originalCreate=MirProgress.create;MirProgress.create=(nick,avatar)=>{const index=avatarIndex(avatar),value=String(nick||"").trim().replace(/\s+/g," ");let profile;if(value.length<=18){profile=originalCreate(value,index)}else{const safe=value.replace(/[^А-Яа-яЁёA-Za-z0-9 _-]/g,"").slice(0,32);if(safe.length<2)throw Error("Введите игровой ник — от 2 до 32 символов");const data=MirProgress.load();profile={id:`child-${Date.now()}-${Math.random().toString(36).slice(2,7)}`,nick:safe,avatar:index,avatarId:avatars[index-1].id,sparks:0,best:{forest:0,river:0,volcano:0},completed:{forest:0,river:0,volcano:0},attempts:{},daily:{},createdAt:Date.now(),updatedAt:Date.now()};data.profiles.push(profile);data.activeId=null;MirProgress.save(data);return profile}const data=MirProgress.load(),saved=data.profiles.find(item=>item.id===profile.id);if(saved&&saved.avatarId!==avatars[index-1].id){saved.avatar=index;saved.avatarId=avatars[index-1].id;MirProgress.save(data);return saved}return profile};$("#profileNick").maxLength=32}
  enableFullGeneratedNicks();
  migrateAvatarCollection();
  migrateRemovedQualities();
  if(!gate.hidden&&!chooseView.hidden)showChooser();
  setupCreateTools();
  gate.querySelector(".gate-panel").append(document.querySelector(".create-avatar-preview"));
  decorateAvatars();
  refreshAvatarDisplay();
  new MutationObserver(()=>{decorateAvatars();refreshAvatarDisplay()}).observe(document.body,{subtree:true,childList:true,attributes:true,attributeFilter:["src"]});
  const houseMarker=document.querySelector('[data-station="kindergarten"]');
  houseMarker?.addEventListener("click",event=>{event.preventDefault();event.stopImmediatePropagation();openProfile("profile")},{capture:true});
  $("#ratingButton").addEventListener("click",event=>{event.preventDefault();event.stopImmediatePropagation();openProfile("rating")},{capture:true});
})();
