(function(){"use strict";
const A="../assets/games/articulation-cliff/",$=s=>document.querySelector(s),screens={title:$("#titleScreen"),game:$("#gameScreen"),final:$("#finalScreen")};
const exercises=[
 {id:"frog",title:"Лягушка",text:"Улыбнись широко-прешироко и удерживай улыбку!",image:"card-frog.png"},
 {id:"fence",title:"Заборчик",text:"Улыбнись, покажи ровные зубки и сомкни их. Получился крепкий заборчик!",image:"card-fence.png"},
 {id:"pancake",title:"Блинчик",text:"Улыбнись, приоткрой ротик и положи широкий спокойный язычок на нижнюю губу",image:"card-pancake.png"},
 {id:"hill",title:"Горка",text:"Открой ротик. Спрячь кончик язычка за нижние зубки, а спинку подними горкой",image:"card-hill.png"},
 {id:"brush",title:"Чистим зубки",text:"Улыбнись и почисти язычком нижние зубки изнутри",image:"card-brush-teeth.png"},
 {id:"clock",title:"Часики",text:"Открой ротик и двигай язычком от одного уголка губ к другому: тик-так!",image:"card-clock.png"}
];
const state={deck:[],first:null,second:null,locked:true,completed:new Set,score:0,raf:0,timers:[],runId:0,exercise:null,testMode:new URLSearchParams(location.search).get("test")==="1"};window.__ARTICULATION_CLIFF__={state,getState:()=>({screen:Object.keys(screens).find(k=>screens[k].classList.contains("active")),score:state.score,completed:[...state.completed],open:[...document.querySelectorAll(".ac-memory-card.open")].length,locked:state.locked})};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b},later=(fn,ms)=>{const id=setTimeout(fn,ms);state.timers.push(id);return id};
function clearMatchFocus(){$("#memoryGrid").classList.remove("has-match");document.querySelectorAll(".ac-memory-card.match-focus,.ac-memory-card.mismatch").forEach(card=>card.classList.remove("match-focus","mismatch"));$("#matchBeam").classList.remove("show");$("#lightParticles").classList.remove("fly")}
function clearWork(){state.runId++;state.timers.forEach(clearTimeout);state.timers=[];cancelAnimationFrame(state.raf);state.raf=0;$("#exerciseModal").hidden=true;$("#igniteButton").disabled=false;clearMatchFocus()}
function show(name){Object.entries(screens).forEach(([key,node])=>node.classList.toggle("active",key===name))}
function renderProgress(){$("#progressText").textContent=`${state.score}/6`;$("#progressCrystals").setAttribute("aria-label",`Зажжено кристаллов: ${state.score} из 6`);$("#progressCrystals").innerHTML=Array.from({length:6},(_,i)=>`<img src="${A}timer/crystal-${i<state.score?"full":"empty"}.png" alt="">`).join("")}
function buildGrid(){$("#memoryGrid").innerHTML=state.deck.map((item,index)=>`<button class="ac-memory-card" style="--float-delay:${-(index%6)*.43}s" type="button" data-index="${index}" aria-label="Закрытая карточка"><img class="back" src="${A}cards/card-back.png" alt=""><img class="face" src="${A}cards/${item.image}" alt="${item.title}"></button>`).join("");$("#memoryGrid").querySelectorAll("button").forEach(button=>button.addEventListener("click",chooseCard))}
function start(){clearWork();state.deck=shuffle(exercises.flatMap(item=>[{...item},{...item}]));state.first=null;state.second=null;state.locked=false;state.completed=new Set;state.score=0;state.exercise=null;window.MirProgress?.startAttempt("cliff");renderProgress();buildGrid();show("game")}
function positionBeam(a,b){const scene=$("#acScene").getBoundingClientRect(),ra=a.getBoundingClientRect(),rb=b.getBoundingClientRect(),x1=ra.left+ra.width/2-scene.left,y1=ra.top+ra.height/2-scene.top,x2=rb.left+rb.width/2-scene.left,y2=rb.top+rb.height/2-scene.top,beam=$("#matchBeam");beam.style.left=`${x1}px`;beam.style.top=`${y1}px`;beam.style.width=`${Math.hypot(x2-x1,y2-y1)}px`;beam.style.transform=`rotate(${Math.atan2(y2-y1,x2-x1)}rad)`;beam.classList.add("show")}
function chooseCard(event){const button=event.currentTarget,index=Number(button.dataset.index);if(state.locked||button.classList.contains("open")||button.classList.contains("matched")||state.completed.has(state.deck[index].id))return;button.classList.add("open");button.setAttribute("aria-label",state.deck[index].title);if(state.first===null){state.first=index;return}state.second=index;state.locked=true;const firstButton=$("[data-index='"+state.first+"']"),same=state.deck[state.first].id===state.deck[state.second].id;if(same){firstButton.classList.add("match-focus");button.classList.add("match-focus");$("#memoryGrid").classList.add("has-match");requestAnimationFrame(()=>positionBeam(firstButton,button));later(()=>openExercise(state.deck[index]),420)}else{firstButton.classList.add("mismatch");button.classList.add("mismatch");later(()=>{firstButton.classList.remove("open","mismatch");button.classList.remove("open","mismatch");state.first=state.second=null;state.locked=false},850)}}
function openExercise(exercise){state.exercise=exercise;$("#exerciseTitle").textContent=exercise.title;$("#exerciseText").textContent=exercise.text;$("#crystalFill").style.setProperty("--fill",0);$("#timerText").textContent="10 секунд";$("#igniteButton").disabled=false;$(".ac-exercise").classList.remove("complete");$("#lightParticles").classList.remove("fly");$("#exerciseModal").hidden=false;requestAnimationFrame(()=>$("#igniteButton").focus())}
function ignite(){if(!state.exercise||$("#igniteButton").disabled)return;$("#igniteButton").disabled=true;const run=state.runId,startAt=performance.now(),duration=state.testMode?350:10000;function tick(now){if(run!==state.runId)return;const p=Math.min(1,(now-startAt)/duration);$("#crystalFill").style.setProperty("--fill",p.toFixed(4));$("#timerText").textContent=p<1?`${Math.max(1,Math.ceil((duration-(now-startAt))/1000))} секунд`:"Готово!";if(p<1){state.raf=requestAnimationFrame(tick)}else finishExercise()}state.raf=requestAnimationFrame(tick)}
function finishExercise(){const id=state.exercise.id;if(state.completed.has(id))return;state.completed.add(id);state.score=Math.min(6,state.score+1);window.MirProgress?.correct("cliff");document.querySelectorAll(".ac-memory-card.open").forEach(card=>{card.classList.remove("open");card.classList.add("matched");card.disabled=true});renderProgress();chime();$(".ac-exercise").classList.add("complete");$("#lightParticles").classList.add("fly");const pop=$("#scorePop");pop.hidden=false;pop.classList.remove("show");void pop.offsetWidth;pop.classList.add("show");later(()=>{pop.hidden=true;$("#exerciseModal").hidden=true;clearMatchFocus();state.first=state.second=null;state.exercise=null;if(state.score===6){show("final");requestAnimationFrame(()=>$("#replayButton").focus())}else state.locked=false},1050)}
function chime(){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const ctx=new C,now=ctx.currentTime;[660,880,1100].forEach((frequency,i)=>{const osc=ctx.createOscillator(),gain=ctx.createGain();osc.type="sine";osc.frequency.value=frequency;gain.gain.setValueAtTime(.0001,now+i*.07);gain.gain.exponentialRampToValueAtTime(.045,now+i*.07+.02);gain.gain.exponentialRampToValueAtTime(.0001,now+i*.07+.35);osc.connect(gain).connect(ctx.destination);osc.start(now+i*.07);osc.stop(now+i*.07+.37)});setTimeout(()=>ctx.close(),700)}
$("#playButton").addEventListener("click",start);$("#replayButton").addEventListener("click",start);$("#igniteButton").addEventListener("click",ignite);addEventListener("pagehide",clearWork);
})();
