(function(){"use strict";
const A="./assets/",$=s=>document.querySelector(s),screens={title:$("#titleScreen"),game:$("#gameScreen"),final:$("#finalScreen")};
const exercises=[
 {id:"frog",title:"Лягушка",text:"Улыбнись широко-прешироко и удерживай улыбку!",image:"card-frog.png"},
 {id:"fence",title:"Заборчик",text:"Улыбнись, покажи ровные зубки и сомкни их. Получился крепкий заборчик!",image:"card-fence.png"},
 {id:"pancake",title:"Блинчик",text:"Улыбнись, приоткрой ротик и положи широкий спокойный язычок на нижнюю губу",image:"card-pancake.png"},
 {id:"hill",title:"Горка",text:"Открой ротик. Спрячь кончик язычка за нижние зубки, а спинку подними горкой",image:"card-hill.png"},
 {id:"brush",title:"Чистим зубки",text:"Улыбнись и почисти язычком нижние зубки изнутри",image:"card-brush-teeth.png"},
 {id:"clock",title:"Часики",text:"Открой ротик и двигай язычком от одного уголка губ к другому: тик-так!",image:"card-clock.png"}
];
const state={deck:[],first:null,second:null,locked:true,completed:new Set,score:0,raf:0,timers:[],runId:0,exercise:null,sfx:localStorage.getItem("mir.cliff.sound")!=="off",testMode:new URLSearchParams(location.search).get("test")==="1"};
const audio={ctx:null,active:new Set,exercise:new Set};
function audioContext(){if(!state.sfx)return null;const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;if(!audio.ctx)audio.ctx=new C;if(audio.ctx.state==="suspended")audio.ctx.resume();return audio.ctx}
function stopAudio(nodes=audio.active){nodes.forEach(node=>{try{node.stop()}catch{}try{node.disconnect()}catch{}audio.active.delete(node);audio.exercise.delete(node)});nodes.clear()}
function tone(frequency,duration=.16,volume=.025,delay=0,type="sine",group=audio.active){const ctx=audioContext();if(!ctx)return;const start=ctx.currentTime+delay,osc=ctx.createOscillator(),gain=ctx.createGain();osc.type=type;osc.frequency.setValueAtTime(frequency,start);gain.gain.setValueAtTime(.0001,start);gain.gain.exponentialRampToValueAtTime(volume,start+.018);gain.gain.exponentialRampToValueAtTime(.0001,start+duration);osc.connect(gain).connect(ctx.destination);audio.active.add(osc);group.add(osc);osc.onended=()=>{audio.active.delete(osc);group.delete(osc)};osc.start(start);osc.stop(start+duration+.02)}
function sound(name){if(!state.sfx)return;switch(name){
 case"flip":tone(185,.09,.018,0,"triangle");tone(285,.07,.012,.035,"sine");break;
 case"mismatch":tone(175,.24,.021,0,"sine");tone(135,.28,.015,.11,"triangle");break;
 case"match":tone(620,.3,.028);tone(830,.34,.026,.08);break;
 case"modal":tone(760,.35,.021);tone(1040,.42,.019,.1);break;
 case"ignite":tone(260,.38,.025,0,"triangle");tone(520,.45,.021,.12);break;
 case"success":tone(660,.38,.03);tone(880,.42,.03,.08);tone(1100,.48,.026,.16);break;
 case"spark":tone(1180,.18,.018);tone(1480,.2,.014,.055);break;
 case"celebrate":[523,659,784,1047].forEach((f,i)=>tone(f,.42,.026,i*.12));break;
 case"button":tone(330,.08,.014,0,"triangle");break;
 }}
function startCrystalRise(){stopAudio(audio.exercise);const ctx=audioContext();if(!ctx)return;const now=ctx.currentTime,duration=state.testMode?.35:10,osc=ctx.createOscillator(),gain=ctx.createGain();osc.type="sine";osc.frequency.setValueAtTime(190,now);osc.frequency.exponentialRampToValueAtTime(430,now+duration);gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.008,now+.25);gain.gain.setValueAtTime(.008,Math.max(now+.26,now+duration-.35));gain.gain.exponentialRampToValueAtTime(.0001,now+duration);osc.connect(gain).connect(ctx.destination);audio.active.add(osc);audio.exercise.add(osc);osc.onended=()=>{audio.active.delete(osc);audio.exercise.delete(osc)};osc.start(now);osc.stop(now+duration+.03)}
window.__ARTICULATION_CLIFF__={state,getState:()=>({screen:Object.keys(screens).find(k=>screens[k].classList.contains("active")),score:state.score,completed:[...state.completed],open:[...document.querySelectorAll(".ac-memory-card.open")].length,locked:state.locked})};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b},later=(fn,ms)=>{const id=setTimeout(fn,ms);state.timers.push(id);return id};
function clearMatchFocus(){$("#memoryGrid").classList.remove("has-match");document.querySelectorAll(".ac-memory-card.match-focus,.ac-memory-card.mismatch").forEach(card=>card.classList.remove("match-focus","mismatch"));$("#matchBeam").classList.remove("show");$("#lightParticles").classList.remove("fly")}
function clearWork(){state.runId++;state.timers.forEach(clearTimeout);state.timers=[];cancelAnimationFrame(state.raf);state.raf=0;stopAudio(audio.exercise);$("#exerciseModal").hidden=true;$("#exerciseModal").classList.remove("is-closing");screens.game.classList.remove("exercise-open");$("#igniteButton").disabled=false;clearMatchFocus()}
function totalScore(){return Number(window.MirProgress?.active?.()?.sparks||0)}
function renderTotal(){$("#cliffTotalScore").textContent=String(totalScore())}
function syncSound(){const button=$("#cliffSound");button.style.opacity=state.sfx?"1":".55";button.setAttribute("aria-pressed",String(!state.sfx));button.setAttribute("aria-label",state.sfx?"Выключить игровые звуки":"Включить игровые звуки")}
function show(name){Object.entries(screens).forEach(([key,node])=>node.classList.toggle("active",key===name));$("#cliffScreenStatus").textContent=name==="title"?"Скала артикуляции":name==="final"?"Все 6 кристаллов зажжены":"Найди 6 пар";renderTotal()}
function renderProgress(){$("#progressText").textContent=`${state.score}/6`;$("#progressCrystals").setAttribute("aria-label",`Зажжено кристаллов: ${state.score} из 6`);$("#progressCrystals").innerHTML=Array.from({length:6},(_,i)=>`<img src="${A}timer/crystal-${i<state.score?"full":"empty"}.png" alt="">`).join("");renderTotal()}
function buildGrid(){$("#memoryGrid").innerHTML=state.deck.map((item,index)=>`<button class="ac-memory-card" style="--float-delay:${-(index%6)*.43}s" type="button" data-index="${index}" aria-label="Закрытая карточка"><img class="back" src="${A}cards/card-back.png" alt=""><img class="face" src="${A}cards/${item.image}" alt="${item.title}"></button>`).join("");$("#memoryGrid").querySelectorAll("button").forEach(button=>button.addEventListener("click",chooseCard))}
function start(){audioContext();sound("button");clearWork();state.deck=shuffle(exercises.flatMap(item=>[{...item},{...item}]));state.first=null;state.second=null;state.locked=false;state.completed=new Set;state.score=0;state.exercise=null;window.MirProgress?.startAttempt("cliff");renderProgress();buildGrid();show("game")}
function positionBeam(a,b){const scene=$("#acScene").getBoundingClientRect(),ra=a.getBoundingClientRect(),rb=b.getBoundingClientRect(),x1=ra.left+ra.width/2-scene.left,y1=ra.top+ra.height/2-scene.top,x2=rb.left+rb.width/2-scene.left,y2=rb.top+rb.height/2-scene.top,beam=$("#matchBeam");beam.style.left=`${x1}px`;beam.style.top=`${y1}px`;beam.style.width=`${Math.hypot(x2-x1,y2-y1)}px`;beam.style.transform=`rotate(${Math.atan2(y2-y1,x2-x1)}rad)`;beam.classList.add("show")}
function chooseCard(event){const button=event.currentTarget,index=Number(button.dataset.index);if(state.locked||button.classList.contains("open")||button.classList.contains("matched")||state.completed.has(state.deck[index].id))return;audioContext();sound("flip");button.classList.add("open");button.setAttribute("aria-label",state.deck[index].title);if(state.first===null){state.first=index;return}state.second=index;state.locked=true;const firstButton=$("[data-index='"+state.first+"']"),same=state.deck[state.first].id===state.deck[state.second].id;if(same){sound("match");screens.game.classList.add("exercise-open");firstButton.classList.add("match-focus");button.classList.add("match-focus");$("#memoryGrid").classList.add("has-match");requestAnimationFrame(()=>positionBeam(firstButton,button));later(()=>openExercise(state.deck[index]),420)}else{sound("mismatch");firstButton.classList.add("mismatch");button.classList.add("mismatch");later(()=>{firstButton.classList.remove("open","mismatch");button.classList.remove("open","mismatch");state.first=state.second=null;state.locked=false},850)}}
function openExercise(exercise){state.exercise=exercise;$("#exerciseTitle").textContent=exercise.title;$("#exerciseText").textContent=exercise.text;$("#crystalFill").style.setProperty("--fill",0);$("#timerText").textContent="10 секунд";$("#igniteButton").disabled=false;$(".ac-exercise").classList.remove("complete");$("#lightParticles").classList.remove("fly");screens.game.classList.add("exercise-open");$("#exerciseModal").classList.remove("is-closing");$("#exerciseModal").hidden=false;sound("modal");requestAnimationFrame(()=>$("#igniteButton").focus())}
function ignite(){if(!state.exercise||$("#igniteButton").disabled)return;$("#igniteButton").disabled=true;sound("ignite");startCrystalRise();const run=state.runId,startAt=performance.now(),duration=state.testMode?350:10000;function tick(now){if(run!==state.runId)return;const p=Math.min(1,(now-startAt)/duration);$("#crystalFill").style.setProperty("--fill",p.toFixed(4));$("#timerText").textContent=p<1?`${Math.max(1,Math.ceil((duration-(now-startAt))/1000))} секунд`:"Готово!";if(p<1){state.raf=requestAnimationFrame(tick)}else finishExercise()}state.raf=requestAnimationFrame(tick)}
function closeExercise(done){const modal=$("#exerciseModal");stopAudio(audio.exercise);modal.classList.add("is-closing");later(()=>{modal.hidden=true;modal.classList.remove("is-closing");screens.game.classList.remove("exercise-open");done()},220)}
function finishExercise(){const id=state.exercise.id;if(state.completed.has(id))return;state.completed.add(id);state.score=Math.min(6,state.score+1);window.MirProgress?.correct("cliff");document.querySelectorAll(".ac-memory-card.open").forEach(card=>{card.classList.remove("open");card.classList.add("matched");card.disabled=true});renderProgress();stopAudio(audio.exercise);sound("success");later(()=>sound("spark"),260);$(".ac-exercise").classList.add("complete");$("#lightParticles").classList.add("fly");const pop=$("#scorePop");pop.hidden=false;pop.classList.remove("show");void pop.offsetWidth;pop.classList.add("show");later(()=>{pop.hidden=true;closeExercise(()=>{clearMatchFocus();state.first=state.second=null;state.exercise=null;if(state.score===6){sound("celebrate");show("final");requestAnimationFrame(()=>$("#replayButton").focus())}else state.locked=false})},1050)}
$("#playButton").addEventListener("click",start);$("#replayButton").addEventListener("click",start);$("#igniteButton").addEventListener("click",ignite);document.querySelectorAll(".ac-world-tool").forEach(button=>button.addEventListener("click",()=>sound("button")));$("#cliffSound").addEventListener("click",()=>{state.sfx=!state.sfx;localStorage.setItem("mir.cliff.sound",state.sfx?"on":"off");if(state.sfx){audioContext();sound("button")}else stopAudio();syncSound()});syncSound();show("title");addEventListener("pagehide",()=>{clearWork();stopAudio()});
})();
