"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const laneIndex={top:0,middle:1,bottom:2},laneY={top:30,middle:50,bottom:70};
const motionX={start:3,gateCenter:62.25,afterGate:76,rightEdge:102};
const state={config:null,deck:[],round:0,lives:3,score:0,correct:0,lane:'middle',locked:true,paused:false,sfx:true,runId:0,gateProgress:0,boatLeft:motionX.start,frame:null,audio:null,testMode:new URLSearchParams(location.search).get('test')==='1'};
window.__RIVER_GAME_STATE__=state;
const screens={start:$("#startScreen"),game:$("#gameScreen"),victory:$("#victoryScreen"),defeat:$("#defeatScreen")};
const delay=ms=>new Promise(r=>setTimeout(r,state.testMode?Math.min(ms,60):ms));
function showScreen(name){Object.entries(screens).forEach(([key,node])=>node.classList.toggle('active',key===name))}
function stopAudio(){if(state.audio){state.audio.pause();state.audio.currentTime=0;state.audio=null}}
async function play(path,{speech=false,volume=1}={}){if(!speech&&!state.sfx)return;if(speech)stopAudio();const audio=new Audio(path);audio.volume=volume;if(speech)state.audio=audio;try{await audio.play()}catch{return}if(state.testMode){await delay(35);audio.pause();return}return new Promise(resolve=>{let done=false;const finish=()=>{if(!done){done=true;resolve()}};audio.onended=audio.onerror=finish;setTimeout(finish,4000)})}
function showLives(){const box=$("#lives");box.innerHTML='';for(let i=0;i<state.config.startingLives;i++){const img=document.createElement('img');img.className='life';img.src=i<state.lives?state.config.assets.ui.crystalWhole:state.config.assets.ui.crystalLost;img.alt=i<state.lives?'Целый кристалл':'Потерянный кристалл';box.append(img)}}
function fisherYates(source){const deck=[...source];for(let i=deck.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[deck[i],deck[j]]=[deck[j],deck[i]]}return deck}
function validDeck(deck,previousFirst){if(previousFirst&&String(deck[0].id)===previousFirst)return false;for(let i=2;i<deck.length;i++){if(deck[i].correctLane===deck[i-1].correctLane&&deck[i].correctLane===deck[i-2].correctLane)return false}return true}
function createDeck(){const previousFirst=sessionStorage.getItem('riverWordsPreviousFirst');let deck;for(let attempt=0;attempt<500;attempt++){deck=fisherYates(state.config.rounds);if(validDeck(deck,previousFirst))break}if(!validDeck(deck,previousFirst)){deck=fisherYates(state.config.rounds);const index=deck.findIndex((round,i)=>i>0&&String(round.id)!==previousFirst);if(String(deck[0].id)===previousFirst&&index>0)[deck[0],deck[index]]=[deck[index],deck[0]];for(let i=2;i<deck.length;i++){if(deck[i].correctLane===deck[i-1].correctLane&&deck[i].correctLane===deck[i-2].correctLane){const swap=deck.findIndex((round,j)=>j>i&&round.correctLane!==deck[i].correctLane);if(swap>i)[deck[i],deck[swap]]=[deck[swap],deck[i]]}}}state.deck=deck;sessionStorage.setItem('riverWordsPreviousFirst',String(deck[0].id));console.info('[Речка слов] Порядок:',deck.map(round=>round.word).join(' → '));return deck}
function setLane(lane){if(state.locked||state.paused||!(lane in laneY))return;state.lane=lane;$("#boat").style.top=`${laneY[lane]}%`}
function forceLane(lane){state.lane=lane;$("#boat").style.top=`${laneY[lane]}%`}
function setBoatLeft(value){state.boatLeft=value;$("#boat").style.left=`${value}%`}
function clearRound(){if(state.frame)cancelAnimationFrame(state.frame);state.frame=null;state.runId++;state.gateProgress=0;$("#correctEffect").classList.remove('active');$("#wrongEffect").classList.remove('active');$("#boat").classList.remove('spin','boost')}
function boatDuration(){return state.testMode?420:6500}
function moveBoat(runId){return new Promise(resolve=>{let last=performance.now(),elapsed=0;const duration=boatDuration(),from=motionX.start,to=motionX.gateCenter;setBoatLeft(from);const tick=now=>{if(runId!==state.runId)return resolve(false);if(!state.paused){elapsed+=now-last;state.gateProgress=Math.min(1,elapsed/duration);setBoatLeft(from+(to-from)*state.gateProgress)}last=now;if(state.gateProgress<1){state.frame=requestAnimationFrame(tick)}else{state.frame=null;resolve(true)}};state.frame=requestAnimationFrame(tick)})}
function animateBoatTo(to,duration,runId){return new Promise(resolve=>{const from=state.boatLeft,start=performance.now();const tick=now=>{if(runId!==state.runId)return resolve(false);const progress=Math.min(1,(now-start)/(state.testMode?Math.min(duration,80):duration));setBoatLeft(from+(to-from)*(1-Math.pow(1-progress,3)));if(progress<1)state.frame=requestAnimationFrame(tick);else{state.frame=null;resolve(true)}};state.frame=requestAnimationFrame(tick)})}
function animateBoostTo(to,duration,runId,effect){return new Promise(resolve=>{const boatFrom=state.boatLeft,waveFrom=parseFloat(effect.style.left),start=performance.now();const tick=now=>{if(runId!==state.runId)return resolve(false);const progress=Math.min(1,(now-start)/(state.testMode?Math.min(duration,80):duration)),eased=1-Math.pow(1-progress,3),boatLeft=boatFrom+(to-boatFrom)*eased;setBoatLeft(boatLeft);effect.style.left=`${waveFrom+(boatLeft-boatFrom)}%`;if(progress<1)state.frame=requestAnimationFrame(tick);else{state.frame=null;resolve(true)}};state.frame=requestAnimationFrame(tick)})}
async function startRound(){clearRound();const id=state.runId,round=state.deck[state.round];state.locked=true;state.paused=false;$("#gameScreen").classList.remove('paused');forceLane('middle');setBoatLeft(motionX.start);$("#roundCounter").textContent=`Задание ${state.round+1} из ${state.deck.length}`;$("#score").textContent=state.score;$("#wordImage").src=round.image;$("#loading").classList.add('visible');showLives();await play(state.config.assets.effectsAudio.roundStart,{volume:.4});await delay(state.config.timing.roundListenDelayMs);if(id!==state.runId)return;await play(round.audio,{speech:true,volume:1});if(id!==state.runId)return;await delay(600);if(id!==state.runId)return;$("#loading").classList.remove('visible');state.locked=false;const arrived=await moveBoat(id);if(arrived&&id===state.runId)resolveRound(round,id)}
async function resolveRound(round,id){if(state.locked||id!==state.runId)return;state.locked=true;const boat=$("#boat"),selectedLane=state.lane;const exited=await animateBoatTo(motionX.afterGate,900,id);if(!exited||id!==state.runId)return;if(selectedLane===round.correctLane){state.score++;state.correct++;$("#score").textContent=state.score;window.MirProgress?.correct('river');const effect=$("#correctEffect");effect.style.left='75.5%';effect.style.top=`${laneY[selectedLane]}%`;effect.classList.add('active');play(state.config.assets.effectsAudio.correct,{volume:.48});showLives();await delay(460);if(id!==state.runId)return;boat.classList.add('boost');await Promise.all([delay(state.config.timing.feedbackMs),animateBoostTo(motionX.rightEdge,850,id,effect)]);if(id!==state.runId)return;state.round++;if(state.round>=state.config.roundCount)return win();startRound()}else{const effect=$("#wrongEffect");effect.style.left='73.25%';effect.style.top=`${laneY[selectedLane]}%`;effect.classList.add('active');boat.classList.add('spin');play(state.config.assets.effectsAudio.wrong,{volume:.45});state.lives--;showLives();await delay(900);if(id!==state.runId)return;boat.classList.remove('spin');await animateBoatTo(motionX.start,900,id);if(id!==state.runId)return;if(state.lives<=0)return lose();startRound()}}
function prepareGame(){clearRound();stopAudio();createDeck();state.round=0;state.lives=state.config.startingLives;state.score=0;state.correct=0;state.lane='middle';state.locked=true;state.paused=false;$("#score").textContent="0";showLives();forceLane('middle')}
async function begin(){window.MirProgress?.startAttempt('river');showScreen('game');$("#loading").classList.add('visible');await preload();prepareGame();startRound()}
function win(){clearRound();state.locked=true;$("#finalScore").textContent=state.score;$("#finalCorrect").textContent=state.correct;window.MirProgress?.finish('river',{score:state.score,completed:true});showScreen('victory');play(state.config.assets.effectsAudio.victory,{volume:.5})}
function lose(){clearRound();state.locked=true;$("#defeatScore").textContent=state.score;$("#defeatCorrect").textContent=state.correct;showScreen('defeat');$("#retryButton").focus()}
function menu(){clearRound();stopAudio();state.paused=false;$("#instructionModal").hidden=true;showScreen('start')}
function openInstruction(){state.wasPaused=state.paused;state.paused=true;$("#gameScreen").classList.add('paused');$("#instructionModal").hidden=false;$("#closeInstruction").focus()}
function closeInstruction(){if($("#instructionModal").hidden)return;$("#instructionModal").hidden=true;state.paused=Boolean(state.wasPaused);if(!state.paused)$("#gameScreen").classList.remove('paused')}
function toggleSound(){state.sfx=!state.sfx;["#sfxToggle","#startSound"].forEach(s=>{const button=$(s);button.textContent="♫";button.style.opacity=state.sfx?'1':'.55';button.setAttribute('aria-pressed',String(!state.sfx));button.setAttribute('aria-label',state.sfx?'Выключить игровые звуки':'Включить игровые звуки')})}
function loadAsset(path,attempt=0){const url=attempt?`${path}?retry=${attempt}-${Date.now()}`:path;if(path.endsWith('.png'))return new Promise(resolve=>{const img=new Image;let done=false;const finish=ok=>{if(done)return;done=true;if(ok||attempt>=2)resolve(ok);else loadAsset(path,attempt+1).then(resolve)};img.onload=()=>finish(true);img.onerror=()=>finish(false);img.src=url;setTimeout(()=>finish(false),8000)});return new Promise(resolve=>{const audio=new Audio;audio.preload='auto';let done=false;const finish=ok=>{if(done)return;done=true;if(ok||attempt>=2)resolve(ok);else loadAsset(path,attempt+1).then(resolve)};audio.onloadeddata=()=>finish(true);audio.onerror=()=>finish(false);audio.src=url;audio.load();setTimeout(()=>finish(true),1800)})}
async function restoreBrokenImages(){const broken=$$('img').filter(img=>img.getAttribute('src')&&img.complete&&!img.naturalWidth);await Promise.all(broken.map(img=>new Promise(resolve=>{const source=img.getAttribute('src').split('?')[0];img.onload=img.onerror=resolve;img.src=`${source}?restore=${Date.now()}-${Math.random()}`})));const background=state.config.assets.background;const image=new Image;await new Promise(resolve=>{image.onload=image.onerror=resolve;image.src=`${background}?scene=${Date.now()}`});if(image.naturalWidth)$("#gameScreen").style.backgroundImage=`url("${image.src}")`}
async function preload(){if(state.preloaded)return;await Promise.race([restoreBrokenImages(),new Promise(resolve=>setTimeout(resolve,12000))]);state.preloaded=true}
$$('#laneButtons button').forEach(b=>b.addEventListener('click',()=>setLane(b.dataset.lane)));
document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeInstruction();return}if(!screens.game.classList.contains('active')||state.paused)return;if(e.key==='ArrowUp'){e.preventDefault();setLane(Object.keys(laneIndex)[Math.max(0,laneIndex[state.lane]-1)])}if(e.key==='ArrowDown'){e.preventDefault();setLane(Object.keys(laneIndex)[Math.min(2,laneIndex[state.lane]+1)])}});
let touchY=null;$("#gameScreen").addEventListener('touchstart',e=>touchY=e.touches[0].clientY,{passive:true});$("#gameScreen").addEventListener('touchend',e=>{if(touchY===null)return;const dy=e.changedTouches[0].clientY-touchY;if(Math.abs(dy)>35)setLane(Object.keys(laneIndex)[Math.max(0,Math.min(2,laneIndex[state.lane]+(dy>0?1:-1)))]);touchY=null},{passive:true});
$("#startButton").addEventListener('click',begin);$("#repeatButton").addEventListener('click',()=>{if(state.deck.length&&screens.game.classList.contains('active'))play(state.deck[state.round].audio,{speech:true})});$$('.open-help').forEach(b=>b.addEventListener('click',openInstruction));$("#closeInstruction").addEventListener('click',closeInstruction);$("#instructionModal .shade").addEventListener('click',closeInstruction);$("#playAgain").addEventListener('click',()=>{window.MirProgress?.startAttempt('river');showScreen('game');prepareGame();startRound()});$("#retryButton").addEventListener('click',()=>{window.MirProgress?.startAttempt('river');showScreen('game');prepareGame();startRound()});$$('.to-menu').forEach(b=>b.addEventListener('click',menu));$("#sfxToggle").addEventListener('click',toggleSound);$("#startSound").addEventListener('click',toggleSound);
fetch('river-game-config.json').then(r=>{if(!r.ok)throw Error('Не удалось загрузить конфигурацию');return r.json()}).then(config=>{state.config=config;document.title=config.title}).catch(error=>{console.error(error);$("#startButton").textContent='ОШИБКА ЗАГРУЗКИ'});
