(function(){
  "use strict";
  const A="../assets/games/flower-meadow/",$=selector=>document.querySelector(selector);
  const scene=$("#fmScene"),hud=$("#fmHud"),playfield=$("#fmPlayfield"),startCard=$("#fmStart"),finalCard=$("#fmFinal"),titleBg=$("#fmTitleBg"),finalBg=$("#fmFinalBg"),gameplayBgs=[...document.querySelectorAll(".fm-gameplay-bg")],breath=$("#fmBreath"),message=$("#fmMessage"),scorePop=$("#fmScorePop"),title=$("#fmTitle"),instruction=$("#fmInstruction"),yashka=$("#fmYashka"),seeds=$("#fmSeeds"),feather=$("#fmFeather"),airRoute=$("#fmAirRoute"),routePath=$("#fmRoutePath"),tryFeather=$("#fmTryFeather"),featherTutorial=$("#fmFeatherTutorial"),rest=$("#fmRest"),restText=$("#fmRestText"),bellsClosed=$("#fmBellsClosed"),bellsAwake=$("#fmBellsAwake"),bellGlow=$("#fmBellGlow"),airPulse=$("#fmAirPulse"),particles=$("#fmParticles");
  const petals=[...document.querySelectorAll(".fm-petals img")],challenges=[$("#fmChallenge1"),$("#fmChallenge2"),$("#fmChallenge3")],arches=[...document.querySelectorAll(".fm-arch-wrap")],routeSegments=[...document.querySelectorAll(".fm-route-segment")],bellParts=[...document.querySelectorAll(".fm-bell-part")],airStreams=[...document.querySelectorAll(".fm-breeze")];
  let stage=0,locked=true,pressing=false,pressStarted=0,raf=0,timers=[],featherState=null,bellCount=0,score=0,awardedStages=new Set;
  const later=(fn,ms)=>{const id=setTimeout(fn,ms);timers.push(id);return id};
  function clearWork(){timers.forEach(clearTimeout);timers=[];cancelAnimationFrame(raf);raf=0;pressing=false;breath.classList.remove("is-active")}
  function showMessage(text,duration=0){message.textContent=text;message.hidden=!text;if(duration)later(()=>{if(message.textContent===text)message.hidden=true},duration)}
  function setYashka(name,alt){yashka.src=A+`trimmed/yashka-${name}-trimmed.png`;yashka.alt=alt}
  function setPetals(count){petals.forEach((petal,index)=>petal.src=A+`ui/progress-petal-${index<count?"filled":"empty"}.png`);document.querySelector(".fm-petals").setAttribute("aria-label",`Собрано лепестков: ${count} из 3`)}
  function showChallenge(index){challenges.forEach((item,i)=>item.hidden=i!==index)}
  function showGameplayState(){titleBg.hidden=true;finalBg.hidden=true;gameplayBgs.forEach(bg=>bg.hidden=false)}
  function prepareScoreAttempt(){score=0;awardedStages=new Set;scorePop.hidden=true;scorePop.classList.remove("is-visible");window.MirProgress?.startAttempt("flower")}
  function awardStage(index){if(awardedStages.has(index))return false;awardedStages.add(index);score=Math.min(3,score+1);window.MirProgress?.correct("flower");scorePop.hidden=false;scorePop.classList.remove("is-visible");void scorePop.offsetWidth;scorePop.classList.add("is-visible");later(()=>{scorePop.hidden=true;scorePop.classList.remove("is-visible")},900);return true}
  function resetGame(){clearWork();stage=1;locked=false;bellCount=0;featherState=null;setPetals(0);showChallenge(0);hud.hidden=false;playfield.hidden=false;finalCard.hidden=true;startCard.hidden=true;rest.hidden=true;message.hidden=true;breath.hidden=false;breath.textContent="Дую";breath.setAttribute("aria-label","Дуть — удерживай кнопку");title.textContent="Разбуди одуванчики";instruction.textContent="Нажми и спокойно удерживай кнопку «Дую»";setYashka("ready","Яшка готов к дыхательному упражнению");seeds.className="fm-seeds";seeds.style.setProperty("--seed-progress",0);$("#fmSprouts").innerHTML="";$("#fmAwakeBg").classList.remove("is-awake");bellsAwake.classList.remove("is-awake");bellsClosed.hidden=false;bellGlow.className="fm-bell-glow glow-one";bellParts.forEach(part=>part.classList.remove("is-awake"));airStreams.forEach(stream=>stream.classList.remove("is-flying"));$("#fmButterflies").innerHTML="";particles.innerHTML="";feather.className="fm-feather";featherTutorial.hidden=true;tryFeather.hidden=true;airRoute.classList.remove("is-preview");routeSegments.forEach(segment=>segment.classList.remove("is-active","is-passed"));positionFeatherAt(0);arches.forEach(arch=>arch.classList.remove("is-active"))}
  function beginPress(event){if(event?.cancelable)event.preventDefault();if(locked||pressing)return;pressing=true;breath.classList.add("is-active");setYashka("blowing","Яшка делает спокойный выдох");if(stage===1){pressStarted=performance.now();seeds.className="fm-seeds is-flying";raf=requestAnimationFrame(stageOneFrame)}else if(stage===2){featherState.last=performance.now();raf=requestAnimationFrame(routeFrame)}else if(stage===3)puffBell()}
  function endPress(event){if(event?.cancelable)event.preventDefault();if(!pressing)return;pressing=false;breath.classList.remove("is-active");setYashka("ready","Яшка отдыхает после выдоха");if(stage===1){cancelAnimationFrame(raf);const elapsed=performance.now()-pressStarted;if(elapsed>=2850)completeOne();else retryOne()}else if(stage===2){cancelAnimationFrame(raf);raf=0}}
  function stageOneFrame(now){if(!pressing||stage!==1)return;const progress=Math.min(1,(now-pressStarted)/3000);seeds.style.setProperty("--seed-progress",progress.toFixed(3));if(now-pressStarted>=3000)return completeOne();raf=requestAnimationFrame(stageOneFrame)}
  function retryOne(){locked=true;seeds.className="fm-seeds is-falling";showMessage("Пушинки почти долетели. Отдохнём и попробуем ещё раз!");later(()=>{seeds.className="fm-seeds";seeds.style.setProperty("--seed-progress",0);message.hidden=true;locked=false},1800)}
  function completeOne(){if(locked)return;locked=true;pressing=false;cancelAnimationFrame(raf);breath.classList.remove("is-active");seeds.style.setProperty("--seed-progress",1);setPetals(1);awardStage(1);growFlowers();showMessage("Получен первый волшебный лепесток!",1000);later(()=>restPause("Отдохнём. Спокойный вдох носом.",startTwo),1100)}
  function growFlowers(){const box=$("#fmSprouts");for(let i=0;i<8;i++){const flower=document.createElement("i");flower.style.left=`${8+i*11}%`;flower.style.background=["#ffd86c","#ff9fc4","#bda7ff"][i%3];flower.style.animationDelay=`${i*.07}s`;box.append(flower)}}
  function restPause(text,next){locked=true;breath.hidden=true;rest.hidden=false;restText.textContent=text;later(()=>{rest.hidden=true;next()},3000)}
  function positionFeatherAt(progress){const length=routePath.getTotalLength(),point=routePath.getPointAtLength(Math.max(0,Math.min(1,progress))*length);feather.style.left=`${point.x/16}%`;feather.style.top=`${point.y/9}%`}
  function makeFeatherState(){const lengths=routeSegments.map(segment=>segment.getTotalLength()),total=lengths.reduce((sum,length)=>sum+length,0),ends=[];lengths.reduce((sum,length)=>{const next=sum+length;ends.push(next/total);return next},0);return{progress:0,segment:0,last:performance.now(),ends}}
  function updateRouteState(){routeSegments.forEach((segment,index)=>{segment.classList.toggle("is-passed",index<featherState.segment);segment.classList.toggle("is-active",index===featherState.segment)});arches.forEach((arch,index)=>arch.classList.toggle("is-active",index===featherState.segment))}
  function startTwo(){stage=2;locked=true;showChallenge(1);title.textContent="Проведи пёрышко";instruction.textContent="Посмотри, как свет проходит по волшебной дорожке";breath.hidden=true;breath.textContent="Дую";setYashka("ready","Яшка готов провести пёрышко");featherState=null;positionFeatherAt(0);featherTutorial.hidden=false;tryFeather.hidden=true;airRoute.classList.add("is-preview");routeSegments.forEach(segment=>segment.classList.remove("is-active","is-passed"));arches.forEach(arch=>arch.classList.remove("is-active"));later(()=>{airRoute.classList.remove("is-preview");tryFeather.hidden=false;tryFeather.focus()},2600)}
  function startFeatherFlight(){if(stage!==2||!locked)return;featherTutorial.hidden=true;instruction.textContent="Зажми «Дую» — пёрышко полетит по волшебной дорожке";breath.hidden=false;locked=false;featherState=makeFeatherState();positionFeatherAt(0);updateRouteState()}
  function routeFrame(now){if(stage!==2||locked||!pressing)return;const state=featherState,dt=Math.min(.05,(now-state.last)/1000||.016);state.last=now;state.progress=Math.min(state.ends[state.segment],state.progress+dt*.105);positionFeatherAt(state.progress);if(state.progress>=state.ends[state.segment]-.0001)return finishRouteSegment();raf=requestAnimationFrame(routeFrame)}
  function finishRouteSegment(){const completed=featherState.segment;pressing=false;locked=true;cancelAnimationFrame(raf);raf=0;breath.classList.remove("is-active");setYashka("ready","Яшка спокойно отдыхает после выдоха");routeSegments[completed].classList.remove("is-active");routeSegments[completed].classList.add("is-passed");arches[completed].classList.remove("is-active");const replies=["Первая арка пройдена! Отдохни немного.","Получилось! Впереди ещё одна арка.","Пёрышко прошло весь воздушный путь!"];showMessage(replies[completed]);if(completed===2){later(completeTwo,1500);return}later(()=>{featherState.segment++;updateRouteState();message.hidden=true;instruction.textContent=`Зажми «Дую» и проведи пёрышко через арку ${featherState.segment+1}`;locked=false},1800)}
  function completeTwo(){locked=true;pressing=false;cancelAnimationFrame(raf);breath.classList.remove("is-active");setPetals(2);awardStage(2);showMessage("Получен второй волшебный лепесток!",1000);later(()=>restPause("Отдохнём. Плечи спокойно, вдох носом.",startThree),1100)}
  function startThree(){stage=3;locked=false;showChallenge(2);title.textContent="Разбуди цветочные колокольчики";instruction.textContent="Три коротких выдоха — следуй за светом";breath.hidden=false;breath.textContent="Пых!";breath.setAttribute("aria-label","Короткий выдох Пых");setYashka("ready","Яшка готов разбудить колокольчики");showMessage("Розовый цветок ждёт первый короткий выдох",1300)}
  function puffBell(){if(stage!==3||locked)return;const index=bellCount++,count=index+1,stream=airStreams[index];stream.classList.remove("is-flying");requestAnimationFrame(()=>stream.classList.add("is-flying"));bellsClosed.classList.remove("pulse");requestAnimationFrame(()=>bellsClosed.classList.add("pulse"));if(count===3)locked=true;later(()=>{bellParts[index]?.classList.add("is-awake");releaseButterfly(index);if(count<3){bellGlow.className=`fm-bell-glow glow-${count===1?"two":"three"}`;showMessage(count===1?"Теперь сиреневый цветок":"Теперь голубой цветок",900)}else{bellGlow.className="fm-bell-glow is-done";later(completeThree,650)}},780)}
  function releaseButterfly(index){const butterfly=document.createElement("img");butterfly.src=A+"trimmed/magic-butterfly-trimmed.png";butterfly.alt="";butterfly.dataset.flower=String(index+1);$("#fmButterflies").append(butterfly)}
  function completeThree(){bellsAwake.classList.add("is-awake");setPetals(3);awardStage(3);showMessage("Все колокольчики проснулись!",1200);later(finale,1200)}
  function finale(){stage=4;locked=true;breath.hidden=true;message.hidden=true;hud.hidden=true;playfield.hidden=true;rest.hidden=true;gameplayBgs.forEach(bg=>bg.hidden=true);titleBg.hidden=true;finalBg.hidden=false;$("#fmFinalResult").textContent=`Ты прошёл 3 испытания и получил ${score} балла.`;localStorage.setItem("mir.flowerMeadow.completed","true");later(()=>{finalCard.hidden=false;requestAnimationFrame(()=>$("#fmReplay").focus())},500)}
  function makeParticles(){for(let i=0;i<22;i++){const spark=document.createElement("i");spark.style.left=`${18+Math.random()*70}%`;spark.style.top=`${25+Math.random()*55}%`;spark.style.setProperty("--sx",`${-40+Math.random()*80}px`);spark.style.setProperty("--sy",`${-30-Math.random()*80}px`);spark.style.animationDelay=`${Math.random()*.7}s`;particles.append(spark)}}
  breath.addEventListener("pointerdown",event=>{breath.setPointerCapture?.(event.pointerId);beginPress(event)});breath.addEventListener("pointerup",endPress);breath.addEventListener("pointercancel",endPress);breath.addEventListener("lostpointercapture",endPress);
  document.addEventListener("keydown",event=>{if((event.code!=="Space"&&event.key!=="Enter")||event.repeat||startCard.hidden===false||finalCard.hidden===false)return;event.preventDefault();beginPress(event)});document.addEventListener("keyup",event=>{if(event.code!=="Space"&&event.key!=="Enter")return;event.preventDefault();endPress(event)});
  $("#fmStartButton").addEventListener("click",()=>{showGameplayState();prepareScoreAttempt();resetGame()});$("#fmTryFeather").addEventListener("click",startFeatherFlight);$("#fmReplay").addEventListener("click",()=>{showGameplayState();prepareScoreAttempt();resetGame()});window.addEventListener("pagehide",clearWork);
  window.__FLOWER_MEADOW__={getState:()=>({stage,locked,pressing,score,awardedStages:[...awardedStages],petals:petals.filter(p=>p.src.includes("filled")).length,bellCount,featherSegment:featherState?.segment??-1,featherProgress:featherState?.progress||0,tutorialVisible:!featherTutorial.hidden,completed:localStorage.getItem("mir.flowerMeadow.completed")==="true"}),reset:resetGame};
})();
